<?php

namespace AppBundle\Repository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des marques
     */
    public function findList($statut = null)
    {
        return $this->createQueryBuilder('m')
                    ->where('m.statut = :statut')
                    ->orderBy('m.libelle', 'ASC')
                    ->setParameter('statut', $statut)
            ;
    }
}
