<?php

namespace AppBundle\Repository;

/**
 * MontureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontureRepository extends \Doctrine\ORM\EntityRepository
{
}
