<?php

namespace AppBundle\Repository;

/**
 * MontureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontureRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des montures
     */
    public function findList($statut = null)
    {
        if ($statut){
            return $this->createQueryBuilder('m')
                        ->leftJoin('m.marque', 'ma')
                        ->where('m.statut = 1')->andWhere('m.stock > 0')
                        ->orderBy('m.reference', 'ASC')
                ;
        }else{
            return $this->createQueryBuilder('mo')
                        ->leftJoin('mo.marque', 'ma')
                        ->orderBy('mo.reference', 'ASC')
                        ->getQuery()->getResult()
                ;
        }
    }

    /**
     * Nombre de monture en stock
     * use DefaultController::index
     */
    public function findNombre($statut = null)
    {
        // Si le statut est nul alors le nombre de monture épuisées
        // sinon le nombre total de montures disponibles
        if ($statut){
            return $this->createQueryBuilder('m')
                        ->select('SUM(m.stock)')
                        ->where('m.statut = 1')
                        ->getQuery()->getSingleScalarResult()
                ;
        }else{
            return $this->createQueryBuilder('m')
                        ->select('count(m.id)')
                        ->where('m.stock = 0')
                        ->getQuery()->getSingleScalarResult()
                ;
        }
    }
}
