<?php

namespace AppBundle\Repository;

/**
 * PenicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenicheRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
        return $this->createQueryBuilder('p')->where('p.flag <> 1')->orWhere('p.flag IS NULL')->orderBy('p.numero', 'ASC');
    }
}
