<?php

namespace AppBundle\Repository;

/**
 * TraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des traiteemnts
     */
    public function findList($statut = null)
    {
        if ($statut){
            return $this->createQueryBuilder('t')
                        ->where('t.statut = 1')->orderBy('t.libelle', 'ASC')
                ;
        }else{
            return $this->createQueryBuilder('t')->orderBy('t.libelle', 'ASC')->getQuery()->getResult();
        }
    }
}
