<?php

namespace AppBundle\Repository;

/**
 * TypeverreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeverreRepository extends \Doctrine\ORM\EntityRepository
{
}
